name: arb_translate_example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # for localization
    sdk: flutter
  intl: ^0.18.0 # for localization

dev_dependencies:
  flutter_lints: ^4.0.0
  arb_translate: ^0.0.1 # auto-generate localization files

flutter:
  uses-material-design: true
  generate: true # for generating l10n files
